# Generated by Django 2.2.12 on 2020-04-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img_path', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
