# Generated by Django 3.0.5 on 2020-04-28 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='coffee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_list', to='foods.Coffee'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='accounts.Order'),
        ),
    ]
