# Generated by Django 3.0.5 on 2020-04-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_eng', models.CharField(max_length=255)),
                ('img_path', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=255)),
                ('category_eng', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img_path', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
