# Generated by Django 2.2.12 on 2020-04-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_year',
            field=models.IntegerField(default=20200422),
            preserve_default=False,
        ),
    ]
