# Generated by Django 2.2.12 on 2020-04-22 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200422_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_list',
            old_name='food_id',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='order_list',
            old_name='order_id',
            new_name='order',
        ),
    ]
